### ISSUE TITLE
请问可以发文字以外的消息吗

### ISSUE THREAD

**Issue by newcovid** [ffreemt/nb2chan#1]
小白疑惑，比如表情或者图片之类的如何推送呢，还有转义类的字符

**Comment by ffreemt** [comment]
目前只实现和测试了发文字。理论上是可以实现发表情和图片的。或许以后实现一下。

**Comment by newcovid** [comment]
感谢回答



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月7日(星期一) 晚上7:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ffreemt/nb2chan] 请问可以发文字以外的消息吗 (Issue #1)





 
目前只实现和测试了发文字。理论上是可以实现发表情和图片的。或许以后实现一下。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
