### ISSUE TITLE
大佬不适配下onebot v11吗

### ISSUE THREAD

**Issue by ghost** [ffreemt/nb2chan#2]
希望在onebot v11上可以用，小白自己改不会
万分感谢！

**Comment by ffreemt** [comment]
nb2chan 本身是用不到适配器的。只是里面的 bot.py 和 mecho.py 需要改。其实这两个文件在dev分支已经改了适配器，忘记合并到master分支。现在也合并过来了。谢谢大佬提醒。

**Comment by ghost** [comment]
大佬，我使用了dev版本，nonebot2与cqhttp连接时报错403
![报错页面](https://user-images.githubusercontent.com/54128025/189485606-c7593011-82d4-4cd8-9456-315dc9ed0ab0.png)
cqhttp的配置如图：
![cqhttp](https://user-images.githubusercontent.com/54128025/189485639-b1f29b97-1cd1-4e54-a919-c2372552e6c9.png)
bot.py配置如图：
![I`}G(3UC4QZ7X {RP9_ KBH](https://user-images.githubusercontent.com/54128025/189485669-5bcba0ed-e8ec-4aa1-9490-77b0241c4563.png)

求解答
多谢！

**Comment by ffreemt** [comment]
两边的端口不匹配好像，一个8680，一个9988？

**Comment by ffreemt** [comment]
你应该用自己的 `bot.py`。 然后`pip install nb2chan`，再在`bot.py`里 `import nbchan`。 库里的bot.py 只是个例子，因为每个人的配置可能都不一样。

**Comment by ffreemt** [comment]
仔细看了一下，两边的端口是匹配的。hmm.... 为什么连不上呢

**Comment by ghost** [comment]
不知道，别的bot都行，就很神奇。没找到问题。多谢开发者帮助！
