### ISSUE TITLE
怎么修改默认的DEMO_TOKEN

### ISSUE THREAD

**Issue by QwindF** [ffreemt/nb2chan#3]
怎么修改默认的DEMO_TOKEN

**Comment by QwindF** [comment]
说错了（，怎么修改默认的token

**Comment by ffreemt** [comment]
试试在当前目录里开一个名为`.env.nb2chan`,  里面内容：
```
NB2CHAN_TOKEN_LIST=["a", "b"]
```
注意，必须是双引号。等号两边可留空格。

不行的话再反馈一下，我自己来试试。

**Comment by QwindF** [comment]
谢谢，可以了。
希望加一个可以向群里发消息的功能
